---
- name: Create /etc/passwd file with root ownership and 0600 permissions
  hosts: your_target_host  # Replace with the appropriate target host or group

  tasks:
    - name: Create /etc/passwd file
      ansible.builtin.file:
        path: /etc/passwd
        state: touch
        mode: '0600'
        owner: root
        group: root
